name: simulation
root: ./
startup_window: hover_mode
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=f450; export ODOMETRY_TYPE=gps; export WORLD_NAME=simulation
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_simulation simulation.launch world_name:=grass_plane gui:=true
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
  - status:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        - waitForSimulation; spawn_uav 1 --file uav1_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 2 --file uav2_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 3 --file uav3_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 4 --file uav4_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
  - control:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general core.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general core.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general core.launch
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_general core.launch
  - automatic_start:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
  - hover_mode:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; history -s 'rosrun flocking send_command start_hover_mode uav1 uav2 uav3 uav4'
  - swarming_mode:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; history -s 'rosrun flocking send_command start_swarming_mode uav1 uav2 uav3 uav4'
  - takeoff:
      layout: tiled
      panes:
        # #{ uav1
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav2
        - 'export UAV_NAME=uav2;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav3
        - 'export UAV_NAME=uav3;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav4
        - 'export UAV_NAME=uav4;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
  - sensor_neighbor:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch flocking sensor_neighbor.launch
        - export UAV_NAME=uav2; waitForRos; roslaunch flocking sensor_neighbor.launch
        - export UAV_NAME=uav3; waitForRos; roslaunch flocking sensor_neighbor.launch
        - export UAV_NAME=uav4; waitForRos; roslaunch flocking sensor_neighbor.launch
  - formation:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch flocking formation.launch
        - export UAV_NAME=uav2; waitForRos; roslaunch flocking formation.launch
        - export UAV_NAME=uav3; waitForRos; roslaunch flocking formation.launch
        - export UAV_NAME=uav4; waitForRos; roslaunch flocking formation.launch
