frame: "fcu_untilted"

land_at_the_end: true

desired_height: 1.8 # [m] 

rate:
  publish_speed: 2 # [Hz]

flocking:

  duration: 240 # [s]

  # Proximal control parameters
  proximal:
    desired_distance: 6.0 # [m]
    noise: 0.1
    strength_potential: 64.0

  # Magnitude-dependent motion control (MDMC) parameters
  MDMC:
    K1: 0.5 # Linear speed gain
    K2: 0.08 # Angular speed gain
    move_forward: 0.10  # [m/s]
