frame: "gps_origin"

land_at_the_end: false

desired_height: 2.5 # [m] 

flocking:
  # Experiment parameters
  auto_start: true
  swarming_after_hover: 10 # [s]
  duration: 120 # [s]

  # Proximal control parameters
  proximal:
    desired_distance: 6.0 # [m]
    noise: 0.1
    strength_potential: 850.0

  # Motion control parameters
  motion:
    K1: 0.5 # Linear gain
    K2: 0.1 # Angular gain
    move_forward: 0.20  # 